name: Tests

on:
  push:
    branches: [ 1.x ]
  pull_request:
    branches: [ 1.x ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.4, 8.5 ]
        laravel: [ 12.*, 13.* ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: 12.*
            testbench: ^10.0
          - laravel: 13.*
            testbench: ^11.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: xdebug
          tools: composer:v2

      - name: Install Aspell
        run: sudo apt-get update && sudo apt-get install -y aspell aspell-en

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-progress --no-interaction

      - name: Run tests (Pest)
        run: composer test
